### ISSUE TITLE
let's use github discussions

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/sparql-12#136]
Has anyone used the new "github discussions"?

https://github.com/unitsofmeasurement/uom-systems/issues/182 says that it would be very beneficial for issues like #129 and gives as example https://github.com/unitsofmeasurement/unit-api/discussions/225. That one is very short so I can't see the benefit...

But most of the issues here are very long (and fruitful!) discussions, and Github is one of the best (and non-intrusive) UI experiences out there, so I believe that if they made a new feature "discussions", we should try it out.

**Comment by VladimirAlexiev** [comment]
Strike 1: https://github.com/FHIR/Ucum-java/issues/19 links to https://github.com/unitsofmeasurement/unit-api/discussions/225 but that discussion doesn't show a back-link.

**Comment by JervenBolleman** [comment]
I think enabling this feature doesn't hurt and might help. So I just went and did it. If "dicussions" don't work then we can always turn it off.

**Comment by afs** [comment]
@VladimirAlexiev - how do you see the difference?

Don't we use issues as discussions; we end up with two mechanisms!

**Comment by TallTed** [comment]
I cannot quickly locate a link to a page telling me about this new github feature... which I'm sure is a failure on my part.  But this suggests that such a link should be provided in this #136 and #137 (which appears at first glance not to be very different from an issue, and not only because discussions apparently share sequence numbering with issues and PRs)...

(There are plenty of examples of useless if not problematic features coming from a certain company with a lot of influence over github, so I'm not sure we can rely on a rubric of "they implemented it, it must be a good thing!")

**Comment by VladimirAlexiev** [comment]
@afs yes, we use issues as discussions, and complex issues like #129 become a tangle of many threads.

Ok, I experimented in #137. It has some threading but is not quote so easy to use.

Strike 2: wastes vertical space by allocating a blank emoji on every comment.

**Comment by VladimirAlexiev** [comment]
> I think enabling this feature doesn't hurt and might help. 

Thanks! The major difference is that in a normal issue like this one, my reply doesn't thread under what I quoted.

**Comment by TallTed** [comment]
> Thanks! The major difference is that in a normal issue like this one, my reply doesn't thread under what I quoted.

But every new reply now threads under the first reply to a (topic?), whether it's a direct response to the original post or otherwise.
