### ISSUE TITLE
internationalize SPARQL currency

### ISSUE THREAD

**Issue by ericprud** [w3c/sparql-12#154]
Add `€` to the SPARQL variable prefixes.

## Why?

For too long have American currency signs dominated the symbol space.
Also, I moved to Europe and keyboards here have this handy character.

## Previous work

https://youtu.be/2mnYf7L7Amw?t=924

## Proposed solution

> [108] | Var | ::= | [VAR1](https://www.w3.org/TR/sparql11-query/#rVAR1) \| [VAR2](https://www.w3.org/TR/sparql11-query/#rVAR2) \| [VAR3](https://www.youtube.com/watch?v=xvFZjo5PgG0)

## Considerations for backward compatibility

€1 can currently be converted to $1.16

**Comment by ericprud** [comment]
Also available for variable prefixes, Greek Question Mark U+037E; it looks like this: `;`.

**Comment by afs** [comment]
‽

**Comment by TallTed** [comment]
Huh.  "Greek Question Mark U+037E" looks like an American Semicolon.  That's just odd.

And today is definitely nowhere near April 1.

What do you have against the Inverted Question Mark, `¿`?

Is the standard Question Mark unavailable anywhere that the `$` is also unavailable, prompting the addition of another symbol for this same SPARQL purpose and position?

Is the Euro Mark used anywhere in the way that `$` is, which provided some justification of the Dollar Sign's inclusion as a user-optional synonym for the `?`?

Is there a reason you're not also suggesting every other Unicode punctuation or currency glyph that's not yet a reserved character?

**Comment by afs** [comment]
The dollar was included because some old connector systems were reported to use `?` as a hard coded, non-escapable, replacement marker.

This is no longer relevant (if it ever was, by the time SPARQL 1.0 was finalized).

>For too long have American currency signs

The US is just one country that uses the word "dollar" and that currency symbol. Namibia and Australia, for example, have "dollars" and use `$`. There are other uses of "$" for currency that isn't called dollar [if we believe wikipedia].

There are more countries in the world that use "$", than use "€".

If we want to equitable, we need a symbol that inconveniences everyone evenly, because there is no worldwide uniform maximum for convenience.

∈ (set membership symbol) for example.

**Comment by ericprud** [comment]
Hopefully https://youtu.be/2mnYf7L7Amw?t=924 has entertained folks. I'm disappointed that SPARQL did not explicitly make the cut for contributions to the terrible language; we must strive to do better.
